# Generated by Django 3.2.9 on 2021-12-28 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('0', 'Sell'), ('1', 'Buy')], default='0', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='account', to='finance.useraccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
